version: '3.9' 
services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/production/backend.conf:/etc/nginx/conf.d/default.conf
      - app_media:/app/media
    depends_on:
      - app
  app:
    restart: always
    expose:
      - "8000"
    volumes:
      - app_media:/app/media
    env_file:
      - website/.env
    depends_on:
      - database
  database:
    restart: always
    env_file:
      - database/.env
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql