#Join file compose, prod, traefik, amd64
version: '3.9'
volumes:
  app_media: {}
  db_data: {}
services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/production/backend.conf:/etc/nginx/conf.d/default.conf
      - app_media:/app/media
    depends_on:
      - app
    labels:
      - traefik.http.routers.${TRAEFIK_ROUTE}.rule=Host(${TRAEFIK_APP_DOMAIN})
      - traefik.http.routers.${TRAEFIK_ROUTE}.tls=true
      - traefik.http.routers.${TRAEFIK_ROUTE}.tls.certresolver=lets-encrypt
      - traefik.port=${TRAEFIK_APP_PORT}
    networks:
      - web
      - internal
  app:
    image: ${IMAGE}
    restart: always
    expose:
      - "8000"
    volumes:
      - app_media:/app/media
    labels:
      - traefik.enable=false
    environment:
      {
        APP_DB_TYPE: mysql,
        APP_HOST_DB: database,
        APP_PORT_DB: 3306,
        APP_NAME_DB: app_db,
        APP_USER_DB: db_user,
        APP_PASSWORD_DB: "${APP_PASSWORD_DB}",
        APP_SECRET_KEY: "${APP_SECRET_KEY}",
        DJANGO_SETTINGS_MODULE: website.settings.production,
        APP_CSRF_TRUSTED_ORIGINS: "http://localhost,https://localhost"
      }
    depends_on:
      - database
    networks:
      - internal
  database:
    image: liupeng0518/mysql:5.7-arm64
    restart: always
    labels:
      - traefik.enable=false
    environment:
      {
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}",
        MYSQL_DATABASE: app_db,
        MYSQL_USER: db_user,
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      }
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
networks:
  web:
    external: true
  internal:
    external: false
