version: '3.9' 
volumes:
  app_media: {}
  db_data: {}
services:
  app:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - app_media:/app/media
    env_file:
      - backend.env
    environment:
      - DJANGO_SETTINGS_MODULE=website.settings.dev
    depends_on:
      - database
  database:
    image: mysql:5.7
    restart: always
    env_file:
      - database.env
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql