# Generated by Django 4.1.2 on 2022-10-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("home", "0003_photos_homepage_about_content_homepage_about_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
