# Generated by Django 4.1.2 on 2022-10-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_events_links_alter_organizers_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="state",
            field=models.CharField(
                choices=[
                    ("past", "Evento Pasado"),
                    ("current", "Evento Actual"),
                    ("upcoming", "Próximo Evento"),
                ],
                default="past",
                max_length=20,
            ),
        ),
    ]
