# Generated by Django 4.1.2 on 2022-10-28 01:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("home", "0008_events_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="externalRaws",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external",
                        wagtail.blocks.StructBlock(
                            [("rawHTML", wagtail.blocks.RawHTMLBlock(required=False))]
                        ),
                    )
                ],
                blank=True,
                use_json_field=None,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
