# Generated by Django 4.1.2 on 2022-10-28 17:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_events_links_alter_homepage_links_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="externalContentFooter",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external",
                        wagtail.blocks.StructBlock(
                            [("rawHTML", wagtail.blocks.RawHTMLBlock(required=False))]
                        ),
                    )
                ],
                blank=True,
                use_json_field=None,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="externalContentMiddle",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external",
                        wagtail.blocks.StructBlock(
                            [("rawHTML", wagtail.blocks.RawHTMLBlock(required=False))]
                        ),
                    )
                ],
                blank=True,
                use_json_field=None,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="externalScripts",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "rawScripts",
                                    wagtail.blocks.RawHTMLBlock(required=False),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=None,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="externalStyles",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external",
                        wagtail.blocks.StructBlock(
                            [("rawStyles", wagtail.blocks.RawHTMLBlock(required=False))]
                        ),
                    )
                ],
                blank=True,
                use_json_field=None,
            ),
        ),
    ]
