# Generated by Django 4.1.2 on 2022-12-16 03:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_homepage_externalcontentfooter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizers",
            name="about",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="organizers",
            name="detail",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
